### ISSUE TITLE
Screen is permanently dimmed

### ISSUE THREAD

**Issue by Qile0317** [datbnh/ScreenDimmer#6]
I downloaded the program, decreased the brightness, and closed the program on an windows 11 laptop, but the dimness never went away and reopening the program to increase the brightness didn't help. How do I get rid of this overlay?

**Comment by datbnh** [comment]
Hi, thanks for your query.

The way the program works is that it renders a semi-transparent layer as a top-most window. If you close the program, the overlay window for sure will go away.

If restarting Windows could not fix it, it is something related to your laptop itself, as the program does not have a start-with-window feature. Make sure to check the brightness setting of the monitor itself.

This has been re-tested on Windows 11.
